name: Android Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          buildozer_version: stable
          command: buildozer android debug
          repository_display_name: PhoneSpeed

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: bin/*.apk
